<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(XuiRuntimeIdentifier)</RuntimeIdentifier>
    <IsXuiSample>true</IsXuiSample>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsAotCompatible>true</IsAotCompatible>
    <ApplicationManifest>..\..\..\demo\xui.manifest</ApplicationManifest>
    <XuiHotReload>false</XuiHotReload>
  </PropertyGroup>
  <Import Project="..\Xui.Declarative.targets" />
</Project>
