<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <NuspecFile>$(MSBuildThisFileDirectory)Xui.Experimental.Windows.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildThisFileDirectory)..\..</NuspecBasePath>
    <NuspecProperties>version=$(PackageVersion);managedRoot=$(XuiWindowsDirectory);nativeRoot=$(XuiNativeDirectory);rid=$(XuiNativeRuntimeIdentifier)</NuspecProperties>
  </PropertyGroup>
</Project>
