<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\..\..\packaging\experimental\Package.props" />
  <PropertyGroup>
    <PackageId>Xui.Experimental.Web</PackageId>
    <StaticWebAssetBasePath>_content/Xui.Web</StaticWebAssetBasePath>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedPlatform>browser</SupportedPlatform>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <ProjectReference Include="..\Xui.Portable\Xui.Portable.csproj" />
  </ItemGroup>
</Project>
