<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WindowsPortableTests" />
    <ProjectReference Include="..\Xui.Portable\Xui.Portable.csproj" />
    <ProjectReference Include="..\..\Xui\Xui.csproj" />
  </ItemGroup>
</Project>
