<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xui.Experimental.Portable" Version="__XUI_PORTABLE_VERSION__" />
    <PackageReference Include="Xui.Experimental.Compiler" Version="__XUI_PORTABLE_VERSION__" PrivateAssets="all" />
  </ItemGroup>
</Project>
