<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(XuiRuntimeIdentifier)</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationManifest>..\..\..\demo\xui.manifest</ApplicationManifest>
  </PropertyGroup>
  <Import Project="..\Xui.Native.targets" />
  <ItemGroup>
    <ProjectReference Include="..\Xui\Xui.csproj" />
    <ProjectReference Include="..\Xui.Generator\Xui.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="..\Designer\DesignerLayout.xui" />
    <AdditionalFiles Include="..\Designer\DesignerDiagnosticsLayout.xui" />
    <AdditionalFiles Include="..\Designer\DesignerSourceSearchLayout.xui" />
    <AdditionalFiles Include="..\Designer\DesignerHierarchyLayout.xui" />
    <AdditionalFiles Include="..\Designer\DesignerInspectorLayout.xui" />
  </ItemGroup>
</Project>
