<Project>
  <Import Project="$(MSBuildThisFileDirectory)Xui.Native.targets" />
  <Import Project="$(MSBuildThisFileDirectory)Xui.Declarative.Common.targets" />
  <PropertyGroup>
    <ApplicationManifest Condition="'$(ApplicationManifest)' == ''">$(MSBuildThisFileDirectory)..\..\demo\xui.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)Xui.Generator\Xui.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)Xui\Xui.csproj" />
    <ProjectReference Condition="'$(XuiHotReload)' == 'true'" Include="$(MSBuildThisFileDirectory)Xui.Development\Xui.Development.csproj" />
  </ItemGroup>
</Project>
