// Generated by bindings/generate_features.py. Do not edit.
use super::*;
impl Window {
    pub fn range_input(&self, name: &str) -> Result<RangeInput> {
        self.feature_create(10, name, None, None, 0).map(RangeInput)
    }
}
impl Window {
    pub fn radio_group(&self, name: &str) -> Result<RadioGroup> {
        self.feature_create(11, name, None, None, 0).map(RadioGroup)
    }
}
impl Window {
    pub fn combo_box(&self, name: &str, editable: bool) -> Result<ComboBox> {
        self.feature_create(12, name, None, None, editable as u32)
            .map(ComboBox)
    }
}
impl Window {
    pub fn numeric_input(&self, name: &str) -> Result<NumericInput> {
        self.feature_create(13, name, None, None, 0)
            .map(NumericInput)
    }
}
impl Window {
    pub fn expander(&self, name: &str, content: &Element) -> Result<Expander> {
        self.feature_create(14, name, Some(content), None, 0)
            .map(Expander)
    }
}
impl Window {
    pub fn progress(&self, name: &str) -> Result<Progress> {
        self.feature_create(15, name, None, None, 0).map(Progress)
    }
}
impl Window {
    pub fn popup(&self, name: &str, content: &Element) -> Result<Popup> {
        self.feature_create(16, name, Some(content), None, 0)
            .map(Popup)
    }
}
impl Window {
    pub fn split_button(&self, name: &str) -> Result<SplitButton> {
        self.feature_create(17, name, None, None, 0)
            .map(SplitButton)
    }
}
impl Window {
    pub fn items_view(&self, name: &str) -> Result<ItemsView> {
        self.feature_create(18, name, None, None, 0).map(ItemsView)
    }
}
impl Window {
    pub fn tree_view(&self, name: &str) -> Result<TreeView> {
        self.feature_create(19, name, None, None, 0).map(TreeView)
    }
}
impl Window {
    pub fn grid(&self, name: &str) -> Result<Grid> {
        self.feature_create(20, name, None, None, 0).map(Grid)
    }
}
impl Window {
    pub fn wrap(&self, name: &str) -> Result<Wrap> {
        self.feature_create(21, name, None, None, 0).map(Wrap)
    }
}
impl Window {
    pub fn adaptive_layout(
        &self,
        name: &str,
        first: &Element,
        second: &Element,
    ) -> Result<AdaptiveLayout> {
        self.feature_create(22, name, Some(first), Some(second), 0)
            .map(AdaptiveLayout)
    }
}
impl Window {
    pub fn command_bar(&self, name: &str) -> Result<CommandBar> {
        self.feature_create(23, name, None, None, 0).map(CommandBar)
    }
}
impl Window {
    pub fn command_surface(&self, name: &str) -> Result<CommandSurface> {
        self.feature_create(24, name, None, None, 0)
            .map(CommandSurface)
    }
}
impl Window {
    pub fn breadcrumb(&self, name: &str) -> Result<Breadcrumb> {
        self.feature_create(25, name, None, None, 0).map(Breadcrumb)
    }
}
impl Window {
    pub fn navigation_pane(&self, name: &str) -> Result<NavigationPane> {
        self.feature_create(26, name, None, None, 0)
            .map(NavigationPane)
    }
}
impl Window {
    pub fn location_picker(&self, name: &str) -> Result<LocationPicker> {
        self.feature_create(27, name, None, None, 0)
            .map(LocationPicker)
    }
}
impl Window {
    pub fn view_picker(&self, name: &str, content: &Element) -> Result<ViewPicker> {
        self.feature_create(28, name, Some(content), None, 0)
            .map(ViewPicker)
    }
}
impl Window {
    pub fn multiline_text(&self, name: &str) -> Result<MultilineText> {
        self.feature_create(29, name, None, None, 0)
            .map(MultilineText)
    }
}
impl Window {
    pub fn rich_text(&self, name: &str) -> Result<RichText> {
        self.feature_create(30, name, None, None, 0).map(RichText)
    }
}
impl Window {
    pub fn password_input(&self, name: &str) -> Result<PasswordInput> {
        self.feature_create(31, name, None, None, 0)
            .map(PasswordInput)
    }
}
impl Window {
    pub fn date_time_picker(
        &self,
        name: &str,
        presentation: DateTimePresentation,
    ) -> Result<DateTimePicker> {
        self.feature_create(32, name, None, None, presentation as u32)
            .map(DateTimePicker)
    }
}
impl Window {
    pub fn inline_status(&self, name: &str) -> Result<InlineStatus> {
        self.feature_create(33, name, None, None, 0)
            .map(InlineStatus)
    }
}
impl Window {
    pub fn color_picker(&self, name: &str) -> Result<ColorPicker> {
        self.feature_create(34, name, None, None, 0)
            .map(ColorPicker)
    }
}
impl Window {
    pub fn content_dialog(&self, name: &str, content: &Element) -> Result<ContentDialog> {
        self.feature_create(35, name, Some(content), None, 0)
            .map(ContentDialog)
    }
}
impl Window {
    pub fn vector_canvas(&self, name: &str) -> Result<VectorCanvas> {
        self.feature_create(36, name, None, None, 0)
            .map(VectorCanvas)
    }
}
impl Window {
    pub fn map_view(&self, name: &str) -> Result<MapView> {
        self.feature_create(37, name, None, None, 0).map(MapView)
    }
}
impl Window {
    pub fn media_playback(&self, name: &str) -> Result<MediaPlayback> {
        self.feature_create(38, name, None, None, 0)
            .map(MediaPlayback)
    }
}
impl Window {
    pub fn web_content(&self, name: &str) -> Result<WebContent> {
        self.feature_create(39, name, None, None, 0).map(WebContent)
    }
}
impl Window {
    pub fn tab_strip(&self, name: &str) -> Result<TabStrip> {
        self.feature_create(40, name, None, None, 0).map(TabStrip)
    }
}
impl Window {
    pub fn split_view(&self, name: &str, first: &Element, second: &Element) -> Result<SplitView> {
        self.feature_create(41, name, Some(first), Some(second), 0)
            .map(SplitView)
    }
}
impl Window {
    pub fn page_view(&self, name: &str) -> Result<PageView> {
        self.feature_create(42, name, None, None, 0).map(PageView)
    }
}
impl Window {
    pub fn data_grid(&self, name: &str) -> Result<DataGrid> {
        self.feature_create(43, name, None, None, 0).map(DataGrid)
    }
}
impl Window {
    pub fn history_chart(&self, name: &str) -> Result<HistoryChart> {
        self.feature_create(44, name, None, None, 0)
            .map(HistoryChart)
    }
}
#[derive(Clone)]
pub struct RangeInput(pub(crate) Element);
pub struct WeakRangeInput(WeakElement);
impl WeakRangeInput {
    pub fn upgrade(&self) -> Option<RangeInput> {
        self.0.upgrade().map(RangeInput)
    }
}
impl RangeInput {
    pub fn weak(&self) -> WeakRangeInput {
        WeakRangeInput(self.0.downgrade())
    }
}
impl std::ops::Deref for RangeInput {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl RangeInput {
    pub fn set_range(&self, value: NumericRange) -> Result<()> {
        self.0.feature_set(
            1,
            sys::FeatureValue {
                a: value.minimum,
                b: value.maximum,
                c: value.small_step,
                d: value.large_step,
                ..value_record()
            },
        )
    }
}
impl RangeInput {
    pub fn range(&self) -> Result<NumericRange> {
        let v = self.0.feature_get(1)?;
        Ok(NumericRange {
            minimum: v.a,
            maximum: v.b,
            small_step: v.c,
            large_step: v.d,
        })
    }
}
impl RangeInput {
    pub fn set_value(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            2,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl RangeInput {
    pub fn value(&self) -> Result<f64> {
        let v = self.0.feature_get(2)?;
        Ok(v.a)
    }
}
impl RangeInput {
    pub fn set_orientation(&self, value: Axis) -> Result<()> {
        self.0.feature_set(
            3,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl RangeInput {
    pub fn set_reversed(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            4,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct RadioGroup(pub(crate) Element);
pub struct WeakRadioGroup(WeakElement);
impl WeakRadioGroup {
    pub fn upgrade(&self) -> Option<RadioGroup> {
        self.0.upgrade().map(RadioGroup)
    }
}
impl RadioGroup {
    pub fn weak(&self) -> WeakRadioGroup {
        WeakRadioGroup(self.0.downgrade())
    }
}
impl std::ops::Deref for RadioGroup {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct ComboBox(pub(crate) Element);
pub struct WeakComboBox(WeakElement);
impl WeakComboBox {
    pub fn upgrade(&self) -> Option<ComboBox> {
        self.0.upgrade().map(ComboBox)
    }
}
impl ComboBox {
    pub fn weak(&self) -> WeakComboBox {
        WeakComboBox(self.0.downgrade())
    }
}
impl std::ops::Deref for ComboBox {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct NumericInput(pub(crate) Element);
pub struct WeakNumericInput(WeakElement);
impl WeakNumericInput {
    pub fn upgrade(&self) -> Option<NumericInput> {
        self.0.upgrade().map(NumericInput)
    }
}
impl NumericInput {
    pub fn weak(&self) -> WeakNumericInput {
        WeakNumericInput(self.0.downgrade())
    }
}
impl std::ops::Deref for NumericInput {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl NumericInput {
    pub fn set_range(&self, value: NumericRange) -> Result<()> {
        self.0.feature_set(
            1,
            sys::FeatureValue {
                a: value.minimum,
                b: value.maximum,
                c: value.small_step,
                d: value.large_step,
                ..value_record()
            },
        )
    }
}
impl NumericInput {
    pub fn range(&self) -> Result<NumericRange> {
        let v = self.0.feature_get(1)?;
        Ok(NumericRange {
            minimum: v.a,
            maximum: v.b,
            small_step: v.c,
            large_step: v.d,
        })
    }
}
impl NumericInput {
    pub fn set_value(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            2,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl NumericInput {
    pub fn value(&self) -> Result<f64> {
        let v = self.0.feature_get(2)?;
        Ok(v.a)
    }
}
#[derive(Clone)]
pub struct Expander(pub(crate) Element);
pub struct WeakExpander(WeakElement);
impl WeakExpander {
    pub fn upgrade(&self) -> Option<Expander> {
        self.0.upgrade().map(Expander)
    }
}
impl Expander {
    pub fn weak(&self) -> WeakExpander {
        WeakExpander(self.0.downgrade())
    }
}
impl std::ops::Deref for Expander {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl Expander {
    pub fn set_expanded(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            5,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl Expander {
    pub fn expanded(&self) -> Result<bool> {
        let v = self.0.feature_get(5)?;
        Ok(v.first != 0)
    }
}
#[derive(Clone)]
pub struct Progress(pub(crate) Element);
pub struct WeakProgress(WeakElement);
impl WeakProgress {
    pub fn upgrade(&self) -> Option<Progress> {
        self.0.upgrade().map(Progress)
    }
}
impl Progress {
    pub fn weak(&self) -> WeakProgress {
        WeakProgress(self.0.downgrade())
    }
}
impl std::ops::Deref for Progress {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl Progress {
    pub fn set_range(&self, value: NumericRange) -> Result<()> {
        self.0.feature_set(
            1,
            sys::FeatureValue {
                a: value.minimum,
                b: value.maximum,
                c: value.small_step,
                d: value.large_step,
                ..value_record()
            },
        )
    }
}
impl Progress {
    pub fn range(&self) -> Result<NumericRange> {
        let v = self.0.feature_get(1)?;
        Ok(NumericRange {
            minimum: v.a,
            maximum: v.b,
            small_step: v.c,
            large_step: v.d,
        })
    }
}
impl Progress {
    pub fn set_value(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            2,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl Progress {
    pub fn value(&self) -> Result<f64> {
        let v = self.0.feature_get(2)?;
        Ok(v.a)
    }
}
impl Progress {
    pub fn set_state(&self, value: ProgressState) -> Result<()> {
        self.0.feature_set(
            6,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl Progress {
    pub fn state(&self) -> Result<ProgressState> {
        let v = self.0.feature_get(6)?;
        ProgressState::from_native(v.first)
    }
}
#[derive(Clone)]
pub struct Popup(pub(crate) Element);
pub struct WeakPopup(WeakElement);
impl WeakPopup {
    pub fn upgrade(&self) -> Option<Popup> {
        self.0.upgrade().map(Popup)
    }
}
impl Popup {
    pub fn weak(&self) -> WeakPopup {
        WeakPopup(self.0.downgrade())
    }
}
impl std::ops::Deref for Popup {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl Popup {
    pub fn dismiss(&self) -> Result<()> {
        self.0.feature_action(5, 0, 0)
    }
}
#[derive(Clone)]
pub struct SplitButton(pub(crate) Element);
pub struct WeakSplitButton(WeakElement);
impl WeakSplitButton {
    pub fn upgrade(&self) -> Option<SplitButton> {
        self.0.upgrade().map(SplitButton)
    }
}
impl SplitButton {
    pub fn weak(&self) -> WeakSplitButton {
        WeakSplitButton(self.0.downgrade())
    }
}
impl std::ops::Deref for SplitButton {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct ItemsView(pub(crate) Element);
pub struct WeakItemsView(WeakElement);
impl WeakItemsView {
    pub fn upgrade(&self) -> Option<ItemsView> {
        self.0.upgrade().map(ItemsView)
    }
}
impl ItemsView {
    pub fn weak(&self) -> WeakItemsView {
        WeakItemsView(self.0.downgrade())
    }
}
impl std::ops::Deref for ItemsView {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl ItemsView {
    pub fn set_presentation(&self, value: ItemsPresentation) -> Result<()> {
        self.0.feature_set(
            28,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl ItemsView {
    pub fn set_offset(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            29,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl ItemsView {
    pub fn select_all(&self) -> Result<()> {
        self.0.feature_action(15, 0, 0)
    }
}
#[derive(Clone)]
pub struct TreeView(pub(crate) Element);
pub struct WeakTreeView(WeakElement);
impl WeakTreeView {
    pub fn upgrade(&self) -> Option<TreeView> {
        self.0.upgrade().map(TreeView)
    }
}
impl TreeView {
    pub fn weak(&self) -> WeakTreeView {
        WeakTreeView(self.0.downgrade())
    }
}
impl std::ops::Deref for TreeView {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl TreeView {
    pub fn set_presentation(&self, value: ItemsPresentation) -> Result<()> {
        self.0.feature_set(
            28,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl TreeView {
    pub fn set_offset(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            29,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl TreeView {
    pub fn select_all(&self) -> Result<()> {
        self.0.feature_action(15, 0, 0)
    }
}
#[derive(Clone)]
pub struct Grid(pub(crate) Element);
pub struct WeakGrid(WeakElement);
impl WeakGrid {
    pub fn upgrade(&self) -> Option<Grid> {
        self.0.upgrade().map(Grid)
    }
}
impl Grid {
    pub fn weak(&self) -> WeakGrid {
        WeakGrid(self.0.downgrade())
    }
}
impl std::ops::Deref for Grid {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct Wrap(pub(crate) Element);
pub struct WeakWrap(WeakElement);
impl WeakWrap {
    pub fn upgrade(&self) -> Option<Wrap> {
        self.0.upgrade().map(Wrap)
    }
}
impl Wrap {
    pub fn weak(&self) -> WeakWrap {
        WeakWrap(self.0.downgrade())
    }
}
impl std::ops::Deref for Wrap {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl Wrap {
    pub fn set_item_width(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            30,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct AdaptiveLayout(pub(crate) Element);
pub struct WeakAdaptiveLayout(WeakElement);
impl WeakAdaptiveLayout {
    pub fn upgrade(&self) -> Option<AdaptiveLayout> {
        self.0.upgrade().map(AdaptiveLayout)
    }
}
impl AdaptiveLayout {
    pub fn weak(&self) -> WeakAdaptiveLayout {
        WeakAdaptiveLayout(self.0.downgrade())
    }
}
impl std::ops::Deref for AdaptiveLayout {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl AdaptiveLayout {
    pub fn set_breakpoint(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            31,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl AdaptiveLayout {
    pub fn set_navigation_extent(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            32,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl AdaptiveLayout {
    pub fn set_navigation_open(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            33,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl AdaptiveLayout {
    pub fn set_compact_navigation(&self, value: CompactNavigation) -> Result<()> {
        self.0.feature_set(
            34,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct CommandBar(pub(crate) Element);
pub struct WeakCommandBar(WeakElement);
impl WeakCommandBar {
    pub fn upgrade(&self) -> Option<CommandBar> {
        self.0.upgrade().map(CommandBar)
    }
}
impl CommandBar {
    pub fn weak(&self) -> WeakCommandBar {
        WeakCommandBar(self.0.downgrade())
    }
}
impl std::ops::Deref for CommandBar {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct CommandSurface(pub(crate) Element);
pub struct WeakCommandSurface(WeakElement);
impl WeakCommandSurface {
    pub fn upgrade(&self) -> Option<CommandSurface> {
        self.0.upgrade().map(CommandSurface)
    }
}
impl CommandSurface {
    pub fn weak(&self) -> WeakCommandSurface {
        WeakCommandSurface(self.0.downgrade())
    }
}
impl std::ops::Deref for CommandSurface {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl CommandSurface {
    pub fn dismiss(&self) -> Result<()> {
        self.0.feature_action(5, 0, 0)
    }
}
#[derive(Clone)]
pub struct Breadcrumb(pub(crate) Element);
pub struct WeakBreadcrumb(WeakElement);
impl WeakBreadcrumb {
    pub fn upgrade(&self) -> Option<Breadcrumb> {
        self.0.upgrade().map(Breadcrumb)
    }
}
impl Breadcrumb {
    pub fn weak(&self) -> WeakBreadcrumb {
        WeakBreadcrumb(self.0.downgrade())
    }
}
impl std::ops::Deref for Breadcrumb {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct NavigationPane(pub(crate) Element);
pub struct WeakNavigationPane(WeakElement);
impl WeakNavigationPane {
    pub fn upgrade(&self) -> Option<NavigationPane> {
        self.0.upgrade().map(NavigationPane)
    }
}
impl NavigationPane {
    pub fn weak(&self) -> WeakNavigationPane {
        WeakNavigationPane(self.0.downgrade())
    }
}
impl std::ops::Deref for NavigationPane {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct LocationPicker(pub(crate) Element);
pub struct WeakLocationPicker(WeakElement);
impl WeakLocationPicker {
    pub fn upgrade(&self) -> Option<LocationPicker> {
        self.0.upgrade().map(LocationPicker)
    }
}
impl LocationPicker {
    pub fn weak(&self) -> WeakLocationPicker {
        WeakLocationPicker(self.0.downgrade())
    }
}
impl std::ops::Deref for LocationPicker {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl LocationPicker {
    pub fn dismiss(&self) -> Result<()> {
        self.0.feature_action(5, 0, 0)
    }
}
#[derive(Clone)]
pub struct ViewPicker(pub(crate) Element);
pub struct WeakViewPicker(WeakElement);
impl WeakViewPicker {
    pub fn upgrade(&self) -> Option<ViewPicker> {
        self.0.upgrade().map(ViewPicker)
    }
}
impl ViewPicker {
    pub fn weak(&self) -> WeakViewPicker {
        WeakViewPicker(self.0.downgrade())
    }
}
impl std::ops::Deref for ViewPicker {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl ViewPicker {
    pub fn dismiss(&self) -> Result<()> {
        self.0.feature_action(5, 0, 0)
    }
}
#[derive(Clone)]
pub struct MultilineText(pub(crate) Element);
pub struct WeakMultilineText(WeakElement);
impl WeakMultilineText {
    pub fn upgrade(&self) -> Option<MultilineText> {
        self.0.upgrade().map(MultilineText)
    }
}
impl MultilineText {
    pub fn weak(&self) -> WeakMultilineText {
        WeakMultilineText(self.0.downgrade())
    }
}
impl std::ops::Deref for MultilineText {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl MultilineText {
    pub fn set_document(&self, value: &str) -> Result<()> {
        self.0.feature_set(
            12,
            sys::FeatureValue {
                text: text(value)?,
                ..value_record()
            },
        )
    }
}
impl MultilineText {
    pub fn set_read_only(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            13,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl MultilineText {
    pub fn read_only(&self) -> Result<bool> {
        let v = self.0.feature_get(13)?;
        Ok(v.first != 0)
    }
}
impl MultilineText {
    pub fn set_maximum_length(&self, value: u64) -> Result<()> {
        self.0.feature_set(
            14,
            sys::FeatureValue {
                first: value,
                ..value_record()
            },
        )
    }
}
impl MultilineText {
    pub fn set_selection(&self, value: TextSelection) -> Result<()> {
        self.0.feature_set(
            15,
            sys::FeatureValue {
                first: value.start,
                second: value.end,
                ..value_record()
            },
        )
    }
}
impl MultilineText {
    pub fn selection(&self) -> Result<TextSelection> {
        let v = self.0.feature_get(15)?;
        Ok(TextSelection {
            start: v.first,
            end: v.second,
        })
    }
}
#[derive(Clone)]
pub struct RichText(pub(crate) Element);
pub struct WeakRichText(WeakElement);
impl WeakRichText {
    pub fn upgrade(&self) -> Option<RichText> {
        self.0.upgrade().map(RichText)
    }
}
impl RichText {
    pub fn weak(&self) -> WeakRichText {
        WeakRichText(self.0.downgrade())
    }
}
impl std::ops::Deref for RichText {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl RichText {
    pub fn set_document(&self, value: &str) -> Result<()> {
        self.0.feature_set(
            12,
            sys::FeatureValue {
                text: text(value)?,
                ..value_record()
            },
        )
    }
}
impl RichText {
    pub fn set_read_only(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            13,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl RichText {
    pub fn read_only(&self) -> Result<bool> {
        let v = self.0.feature_get(13)?;
        Ok(v.first != 0)
    }
}
impl RichText {
    pub fn set_maximum_length(&self, value: u64) -> Result<()> {
        self.0.feature_set(
            14,
            sys::FeatureValue {
                first: value,
                ..value_record()
            },
        )
    }
}
impl RichText {
    pub fn set_selection(&self, value: TextSelection) -> Result<()> {
        self.0.feature_set(
            15,
            sys::FeatureValue {
                first: value.start,
                second: value.end,
                ..value_record()
            },
        )
    }
}
impl RichText {
    pub fn selection(&self) -> Result<TextSelection> {
        let v = self.0.feature_get(15)?;
        Ok(TextSelection {
            start: v.first,
            end: v.second,
        })
    }
}
#[derive(Clone)]
pub struct PasswordInput(pub(crate) Element);
pub struct WeakPasswordInput(WeakElement);
impl WeakPasswordInput {
    pub fn upgrade(&self) -> Option<PasswordInput> {
        self.0.upgrade().map(PasswordInput)
    }
}
impl PasswordInput {
    pub fn weak(&self) -> WeakPasswordInput {
        WeakPasswordInput(self.0.downgrade())
    }
}
impl PasswordInput {
    pub fn as_element(&self) -> &Element {
        &self.0
    }
}
impl PasswordInput {
    pub fn set_maximum_length(&self, value: u64) -> Result<()> {
        self.0.feature_set(
            14,
            sys::FeatureValue {
                first: value,
                ..value_record()
            },
        )
    }
}
impl PasswordInput {
    pub fn set_reveal_allowed(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            17,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct DateTimePicker(pub(crate) Element);
pub struct WeakDateTimePicker(WeakElement);
impl WeakDateTimePicker {
    pub fn upgrade(&self) -> Option<DateTimePicker> {
        self.0.upgrade().map(DateTimePicker)
    }
}
impl DateTimePicker {
    pub fn weak(&self) -> WeakDateTimePicker {
        WeakDateTimePicker(self.0.downgrade())
    }
}
impl std::ops::Deref for DateTimePicker {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct InlineStatus(pub(crate) Element);
pub struct WeakInlineStatus(WeakElement);
impl WeakInlineStatus {
    pub fn upgrade(&self) -> Option<InlineStatus> {
        self.0.upgrade().map(InlineStatus)
    }
}
impl InlineStatus {
    pub fn weak(&self) -> WeakInlineStatus {
        WeakInlineStatus(self.0.downgrade())
    }
}
impl std::ops::Deref for InlineStatus {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl InlineStatus {
    pub fn set_dismissible(&self, value: bool) -> Result<()> {
        self.0.feature_set(
            21,
            sys::FeatureValue {
                first: value as u64,
                ..value_record()
            },
        )
    }
}
impl InlineStatus {
    pub fn dismiss(&self) -> Result<()> {
        self.0.feature_action(5, 0, 0)
    }
}
impl InlineStatus {
    pub fn show(&self) -> Result<()> {
        self.0.feature_action(6, 0, 0)
    }
}
#[derive(Clone)]
pub struct ColorPicker(pub(crate) Element);
pub struct WeakColorPicker(WeakElement);
impl WeakColorPicker {
    pub fn upgrade(&self) -> Option<ColorPicker> {
        self.0.upgrade().map(ColorPicker)
    }
}
impl ColorPicker {
    pub fn weak(&self) -> WeakColorPicker {
        WeakColorPicker(self.0.downgrade())
    }
}
impl std::ops::Deref for ColorPicker {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl ColorPicker {
    pub fn set_value(&self, value: RgbaColor) -> Result<()> {
        self.0.feature_set(
            19,
            sys::FeatureValue {
                first: value.packed(),
                ..value_record()
            },
        )
    }
}
impl ColorPicker {
    pub fn value(&self) -> Result<RgbaColor> {
        let v = self.0.feature_get(19)?;
        Ok(RgbaColor::from_packed(v.first))
    }
}
#[derive(Clone)]
pub struct ContentDialog(pub(crate) Element);
pub struct WeakContentDialog(WeakElement);
impl WeakContentDialog {
    pub fn upgrade(&self) -> Option<ContentDialog> {
        self.0.upgrade().map(ContentDialog)
    }
}
impl ContentDialog {
    pub fn weak(&self) -> WeakContentDialog {
        WeakContentDialog(self.0.downgrade())
    }
}
impl std::ops::Deref for ContentDialog {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl ContentDialog {
    pub fn accept(&self) -> Result<()> {
        self.0.feature_action(7, 0, 0)
    }
}
impl ContentDialog {
    pub fn cancel(&self) -> Result<()> {
        self.0.feature_action(8, 0, 0)
    }
}
#[derive(Clone)]
pub struct VectorCanvas(pub(crate) Element);
pub struct WeakVectorCanvas(WeakElement);
impl WeakVectorCanvas {
    pub fn upgrade(&self) -> Option<VectorCanvas> {
        self.0.upgrade().map(VectorCanvas)
    }
}
impl VectorCanvas {
    pub fn weak(&self) -> WeakVectorCanvas {
        WeakVectorCanvas(self.0.downgrade())
    }
}
impl std::ops::Deref for VectorCanvas {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct MapView(pub(crate) Element);
pub struct WeakMapView(WeakElement);
impl WeakMapView {
    pub fn upgrade(&self) -> Option<MapView> {
        self.0.upgrade().map(MapView)
    }
}
impl MapView {
    pub fn weak(&self) -> WeakMapView {
        WeakMapView(self.0.downgrade())
    }
}
impl std::ops::Deref for MapView {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct MediaPlayback(pub(crate) Element);
pub struct WeakMediaPlayback(WeakElement);
impl WeakMediaPlayback {
    pub fn upgrade(&self) -> Option<MediaPlayback> {
        self.0.upgrade().map(MediaPlayback)
    }
}
impl MediaPlayback {
    pub fn weak(&self) -> WeakMediaPlayback {
        WeakMediaPlayback(self.0.downgrade())
    }
}
impl std::ops::Deref for MediaPlayback {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl MediaPlayback {
    pub fn set_volume(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            24,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
impl MediaPlayback {
    pub fn play(&self) -> Result<()> {
        self.0.feature_action(9, 0, 0)
    }
}
impl MediaPlayback {
    pub fn pause(&self) -> Result<()> {
        self.0.feature_action(10, 0, 0)
    }
}
impl MediaPlayback {
    pub fn stop(&self) -> Result<()> {
        self.0.feature_action(11, 0, 0)
    }
}
impl MediaPlayback {
    pub fn unload(&self) -> Result<()> {
        self.0.feature_action(12, 0, 0)
    }
}
#[derive(Clone)]
pub struct WebContent(pub(crate) Element);
pub struct WeakWebContent(WeakElement);
impl WeakWebContent {
    pub fn upgrade(&self) -> Option<WebContent> {
        self.0.upgrade().map(WebContent)
    }
}
impl WebContent {
    pub fn weak(&self) -> WeakWebContent {
        WeakWebContent(self.0.downgrade())
    }
}
impl std::ops::Deref for WebContent {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl WebContent {
    pub fn stop(&self) -> Result<()> {
        self.0.feature_action(11, 0, 0)
    }
}
impl WebContent {
    pub fn unload(&self) -> Result<()> {
        self.0.feature_action(12, 0, 0)
    }
}
impl WebContent {
    pub fn reload(&self) -> Result<()> {
        self.0.feature_action(13, 0, 0)
    }
}
impl WebContent {
    pub fn focus_content(&self) -> Result<()> {
        self.0.feature_action(14, 0, 0)
    }
}
#[derive(Clone)]
pub struct TabStrip(pub(crate) Element);
pub struct WeakTabStrip(WeakElement);
impl WeakTabStrip {
    pub fn upgrade(&self) -> Option<TabStrip> {
        self.0.upgrade().map(TabStrip)
    }
}
impl TabStrip {
    pub fn weak(&self) -> WeakTabStrip {
        WeakTabStrip(self.0.downgrade())
    }
}
impl std::ops::Deref for TabStrip {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
#[derive(Clone)]
pub struct SplitView(pub(crate) Element);
pub struct WeakSplitView(WeakElement);
impl WeakSplitView {
    pub fn upgrade(&self) -> Option<SplitView> {
        self.0.upgrade().map(SplitView)
    }
}
impl SplitView {
    pub fn weak(&self) -> WeakSplitView {
        WeakSplitView(self.0.downgrade())
    }
}
impl std::ops::Deref for SplitView {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl SplitView {
    pub fn set_ratio(&self, value: f64) -> Result<()> {
        self.0.feature_set(
            35,
            sys::FeatureValue {
                a: value,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct PageView(pub(crate) Element);
pub struct WeakPageView(WeakElement);
impl WeakPageView {
    pub fn upgrade(&self) -> Option<PageView> {
        self.0.upgrade().map(PageView)
    }
}
impl PageView {
    pub fn weak(&self) -> WeakPageView {
        WeakPageView(self.0.downgrade())
    }
}
impl std::ops::Deref for PageView {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl PageView {
    pub fn set_selected_page(&self, value: u64) -> Result<()> {
        self.0.feature_set(
            36,
            sys::FeatureValue {
                first: value,
                ..value_record()
            },
        )
    }
}
#[derive(Clone)]
pub struct DataGrid(pub(crate) Element);
pub struct WeakDataGrid(WeakElement);
impl WeakDataGrid {
    pub fn upgrade(&self) -> Option<DataGrid> {
        self.0.upgrade().map(DataGrid)
    }
}
impl DataGrid {
    pub fn weak(&self) -> WeakDataGrid {
        WeakDataGrid(self.0.downgrade())
    }
}
impl std::ops::Deref for DataGrid {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
impl DataGrid {
    pub fn select_all(&self) -> Result<()> {
        self.0.feature_action(15, 0, 0)
    }
}
#[derive(Clone)]
pub struct HistoryChart(pub(crate) Element);
pub struct WeakHistoryChart(WeakElement);
impl WeakHistoryChart {
    pub fn upgrade(&self) -> Option<HistoryChart> {
        self.0.upgrade().map(HistoryChart)
    }
}
impl HistoryChart {
    pub fn weak(&self) -> WeakHistoryChart {
        WeakHistoryChart(self.0.downgrade())
    }
}
impl std::ops::Deref for HistoryChart {
    type Target = Element;
    fn deref(&self) -> &Element {
        &self.0
    }
}
