// Generated by bindings/generate_features.py. Do not edit.
namespace Xui;
public sealed unsafe partial class Window {
public RangeInput RangeInput(string name) => new(this, FeatureCreate(10, name));
public RadioGroup RadioGroup(string name) => new(this, FeatureCreate(11, name));
public ComboBox ComboBox(string name, bool editable = false) => new(this, FeatureCreate(12, name, mode: editable ? 1u : 0u));
public NumericInput NumericInput(string name) => new(this, FeatureCreate(13, name));
public Expander Expander(string name, Element content) => new(this, FeatureCreate(14, name, content));
public Progress Progress(string name) => new(this, FeatureCreate(15, name));
public Popup Popup(string name, Element content) => new(this, FeatureCreate(16, name, content));
public SplitButton SplitButton(string name) => new(this, FeatureCreate(17, name));
public ItemsView ItemsView(string name) => new(this, FeatureCreate(18, name));
public TreeView TreeView(string name) => new(this, FeatureCreate(19, name));
public Grid Grid(string name) => new(this, FeatureCreate(20, name));
public Wrap Wrap(string name) => new(this, FeatureCreate(21, name));
public AdaptiveLayout AdaptiveLayout(string name, Element first, Element second) => new(this, FeatureCreate(22, name, first, second));
public CommandBar CommandBar(string name) => new(this, FeatureCreate(23, name));
public CommandSurface CommandSurface(string name) => new(this, FeatureCreate(24, name));
public Breadcrumb Breadcrumb(string name) => new(this, FeatureCreate(25, name));
public NavigationPane NavigationPane(string name) => new(this, FeatureCreate(26, name));
public LocationPicker LocationPicker(string name) => new(this, FeatureCreate(27, name));
public ViewPicker ViewPicker(string name, Element content) => new(this, FeatureCreate(28, name, content));
public MultilineText MultilineText(string name) => new(this, FeatureCreate(29, name));
public RichText RichText(string name) => new(this, FeatureCreate(30, name));
public PasswordInput PasswordInput(string name) => new(this, FeatureCreate(31, name));
public DateTimePicker DateTimePicker(string name, DateTimePresentation presentation = DateTimePresentation.Date) => new(this, FeatureCreate(32, name, mode: (uint)presentation));
public InlineStatus InlineStatus(string name) => new(this, FeatureCreate(33, name));
public ColorPicker ColorPicker(string name) => new(this, FeatureCreate(34, name));
public ContentDialog ContentDialog(string name, Element content) => new(this, FeatureCreate(35, name, content));
public VectorCanvas VectorCanvas(string name) => new(this, FeatureCreate(36, name));
public MapView MapView(string name) => new(this, FeatureCreate(37, name));
public MediaPlayback MediaPlayback(string name) => new(this, FeatureCreate(38, name));
public WebContent WebContent(string name) => new(this, FeatureCreate(39, name));
public TabStrip TabStrip(string name) => new(this, FeatureCreate(40, name));
public SplitView SplitView(string name, Element first, Element second) => new(this, FeatureCreate(41, name, first, second));
public PageView PageView(string name) => new(this, FeatureCreate(42, name));
public DataGrid DataGrid(string name) => new(this, FeatureCreate(43, name));
public HistoryChart HistoryChart(string name) => new(this, FeatureCreate(44, name));
public NavigationView NavigationView(string name) => new(this, FeatureCreate(45, name));
public MillerColumns MillerColumns(string name) => new(this, FeatureCreate(46, name));
public ToggleSwitch ToggleSwitch(string name) => new(this, FeatureCreate(48, name));
public ToggleButton ToggleButton(string name) => new(this, FeatureCreate(49, name));
public ProgressRing ProgressRing(string name) => new(this, FeatureCreate(50, name));
public CheckBox CheckBox(string name) => new(this, FeatureCreate(51, name));
public HyperlinkButton HyperlinkButton(string name) => new(this, FeatureCreate(52, name));
public SelectorBar SelectorBar(string name) => new(this, FeatureCreate(53, name));
public InfoBadge InfoBadge(string name) => new(this, FeatureCreate(54, name));
public MenuBar MenuBar(string name) => new(this, FeatureCreate(55, name));
}
public sealed unsafe partial class RangeInput : Control {
internal RangeInput(Window w, ulong h) : base(w,h) { }
public NumericRange Range { get { var v = Features.Get(this,1); return new(v.A,v.B,v.C,v.D); } set => Features.Set(this,1,a: value.Minimum, b: value.Maximum, c: value.SmallStep, d: value.LargeStep); }
public RangeInput SetRange(NumericRange value) { Range = value; return this; }
public double Value { get { var v = Features.Get(this,2); return v.A; } set => Features.Set(this,2,a: value); }
public RangeInput SetValue(double value) { Value = value; return this; }
public Axis Orientation { set => Features.Set(this,3,first: (uint)value); }
public RangeInput SetOrientation(Axis value) { Orientation = value; return this; }
public bool Reversed { set => Features.Set(this,4,first: value ? 1u : 0u); }
public RangeInput SetReversed(bool value) { Reversed = value; return this; }
}
public sealed unsafe partial class RadioGroup : Control {
internal RadioGroup(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class ComboBox : Control {
internal ComboBox(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class NumericInput : Control {
internal NumericInput(Window w, ulong h) : base(w,h) { }
public NumericRange Range { get { var v = Features.Get(this,1); return new(v.A,v.B,v.C,v.D); } set => Features.Set(this,1,a: value.Minimum, b: value.Maximum, c: value.SmallStep, d: value.LargeStep); }
public NumericInput SetRange(NumericRange value) { Range = value; return this; }
public double Value { get { var v = Features.Get(this,2); return v.A; } set => Features.Set(this,2,a: value); }
public NumericInput SetValue(double value) { Value = value; return this; }
}
public sealed unsafe partial class Expander : Control {
internal Expander(Window w, ulong h) : base(w,h) { }
public bool Expanded { get { var v = Features.Get(this,5); return v.First != 0; } set => Features.Set(this,5,first: value ? 1u : 0u); }
public Expander SetExpanded(bool value) { Expanded = value; return this; }
}
public sealed unsafe partial class Progress : Control {
internal Progress(Window w, ulong h) : base(w,h) { }
public NumericRange Range { get { var v = Features.Get(this,1); return new(v.A,v.B,v.C,v.D); } set => Features.Set(this,1,a: value.Minimum, b: value.Maximum, c: value.SmallStep, d: value.LargeStep); }
public Progress SetRange(NumericRange value) { Range = value; return this; }
public double Value { get { var v = Features.Get(this,2); return v.A; } set => Features.Set(this,2,a: value); }
public Progress SetValue(double value) { Value = value; return this; }
public ProgressState State { get { var v = Features.Get(this,6); return (ProgressState)v.First; } set => Features.Set(this,6,first: (uint)value); }
public Progress SetState(ProgressState value) { State = value; return this; }
}
public sealed unsafe partial class Popup : Control {
internal Popup(Window w, ulong h) : base(w,h) { }
public void Dismiss() => Features.Action(this,5);
}
public sealed unsafe partial class SplitButton : Element {
internal SplitButton(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class ItemsView : Control {
internal ItemsView(Window w, ulong h) : base(w,h) { }
public ItemsPresentation Presentation { set => Features.Set(this,28,first: (uint)value); }
public ItemsView SetPresentation(ItemsPresentation value) { Presentation = value; return this; }
public double Offset { get { var v = Features.Get(this,29); return v.A; } set => Features.Set(this,29,a: value); }
public ItemsView SetOffset(double value) { Offset = value; return this; }
public void SelectAll() => Features.Action(this,15);
}
public sealed unsafe partial class TreeView : Control {
internal TreeView(Window w, ulong h) : base(w,h) { }
public ItemsPresentation Presentation { set => Features.Set(this,28,first: (uint)value); }
public TreeView SetPresentation(ItemsPresentation value) { Presentation = value; return this; }
public double Offset { get { var v = Features.Get(this,29); return v.A; } set => Features.Set(this,29,a: value); }
public TreeView SetOffset(double value) { Offset = value; return this; }
public void SelectAll() => Features.Action(this,15);
}
public sealed unsafe partial class Grid : Element {
internal Grid(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class Wrap : Element {
internal Wrap(Window w, ulong h) : base(w,h) { }
public double ItemWidth { set => Features.Set(this,30,a: value); }
public Wrap SetItemWidth(double value) { ItemWidth = value; return this; }
}
public sealed unsafe partial class AdaptiveLayout : Element {
internal AdaptiveLayout(Window w, ulong h) : base(w,h) { }
public double Breakpoint { set => Features.Set(this,31,a: value); }
public AdaptiveLayout SetBreakpoint(double value) { Breakpoint = value; return this; }
public double NavigationExtent { set => Features.Set(this,32,a: value); }
public AdaptiveLayout SetNavigationExtent(double value) { NavigationExtent = value; return this; }
public bool NavigationOpen { set => Features.Set(this,33,first: value ? 1u : 0u); }
public AdaptiveLayout SetNavigationOpen(bool value) { NavigationOpen = value; return this; }
public CompactNavigation CompactNavigation { set => Features.Set(this,34,first: (uint)value); }
public AdaptiveLayout SetCompactNavigation(CompactNavigation value) { CompactNavigation = value; return this; }
}
public sealed unsafe partial class CommandBar : Control {
internal CommandBar(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class CommandSurface : Element {
internal CommandSurface(Window w, ulong h) : base(w,h) { }
public void Dismiss() => Features.Action(this,5);
}
public sealed unsafe partial class Breadcrumb : Control {
internal Breadcrumb(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class NavigationPane : Control {
internal NavigationPane(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class LocationPicker : Element {
internal LocationPicker(Window w, ulong h) : base(w,h) { }
public void Dismiss() => Features.Action(this,5);
}
public sealed unsafe partial class ViewPicker : Element {
internal ViewPicker(Window w, ulong h) : base(w,h) { }
public void Dismiss() => Features.Action(this,5);
}
public sealed unsafe partial class MultilineText : Control {
internal MultilineText(Window w, ulong h) : base(w,h) { }
public string Document { set => Features.Set(this,12,text: value); }
public MultilineText SetDocument(string value) { Document = value; return this; }
public bool ReadOnly { get { var v = Features.Get(this,13); return v.First != 0; } set => Features.Set(this,13,first: value ? 1u : 0u); }
public MultilineText SetReadOnly(bool value) { ReadOnly = value; return this; }
public ulong MaximumLength { set => Features.Set(this,14,first: value); }
public MultilineText SetMaximumLength(ulong value) { MaximumLength = value; return this; }
public TextSelection Selection { get { var v = Features.Get(this,15); return new(v.First,v.Second); } set => Features.Set(this,15,first: value.Start, second: value.End); }
public MultilineText SetSelection(TextSelection value) { Selection = value; return this; }
}
public sealed unsafe partial class RichText : Control {
internal RichText(Window w, ulong h) : base(w,h) { }
public string Document { set => Features.Set(this,12,text: value); }
public RichText SetDocument(string value) { Document = value; return this; }
public bool ReadOnly { get { var v = Features.Get(this,13); return v.First != 0; } set => Features.Set(this,13,first: value ? 1u : 0u); }
public RichText SetReadOnly(bool value) { ReadOnly = value; return this; }
public ulong MaximumLength { set => Features.Set(this,14,first: value); }
public RichText SetMaximumLength(ulong value) { MaximumLength = value; return this; }
public TextSelection Selection { get { var v = Features.Get(this,15); return new(v.First,v.Second); } set => Features.Set(this,15,first: value.Start, second: value.End); }
public RichText SetSelection(TextSelection value) { Selection = value; return this; }
}
public sealed unsafe partial class PasswordInput : Element {
internal PasswordInput(Window w, ulong h) : base(w,h) { }
public ulong MaximumLength { set => Features.Set(this,14,first: value); }
public PasswordInput SetMaximumLength(ulong value) { MaximumLength = value; return this; }
public bool RevealAllowed { set => Features.Set(this,17,first: value ? 1u : 0u); }
public PasswordInput SetRevealAllowed(bool value) { RevealAllowed = value; return this; }
}
public sealed unsafe partial class DateTimePicker : Control {
internal DateTimePicker(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class InlineStatus : Control {
internal InlineStatus(Window w, ulong h) : base(w,h) { }
public bool Dismissible { set => Features.Set(this,21,first: value ? 1u : 0u); }
public InlineStatus SetDismissible(bool value) { Dismissible = value; return this; }
public void Dismiss() => Features.Action(this,5);
public void Show() => Features.Action(this,6);
}
public sealed unsafe partial class ColorPicker : Control {
internal ColorPicker(Window w, ulong h) : base(w,h) { }
public RgbaColor Value { get { var v = Features.Get(this,19); return RgbaColor.FromPacked(v.First); } set => Features.Set(this,19,first: value.Packed); }
public ColorPicker SetValue(RgbaColor value) { Value = value; return this; }
}
public sealed unsafe partial class ContentDialog : Element {
internal ContentDialog(Window w, ulong h) : base(w,h) { }
public void Accept() => Features.Action(this,7);
public void Cancel() => Features.Action(this,8);
}
public sealed unsafe partial class VectorCanvas : Control {
internal VectorCanvas(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class MapView : Control {
internal MapView(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class MediaPlayback : Control {
internal MediaPlayback(Window w, ulong h) : base(w,h) { }
public double Volume { set => Features.Set(this,24,a: value); }
public MediaPlayback SetVolume(double value) { Volume = value; return this; }
public void Play() => Features.Action(this,9);
public void Pause() => Features.Action(this,10);
public void Stop() => Features.Action(this,11);
public void Unload() => Features.Action(this,12);
}
public sealed unsafe partial class WebContent : Control {
internal WebContent(Window w, ulong h) : base(w,h) { }
public void Stop() => Features.Action(this,11);
public void Unload() => Features.Action(this,12);
public void Reload() => Features.Action(this,13);
public void FocusContent() => Features.Action(this,14);
}
public sealed unsafe partial class TabStrip : Control {
internal TabStrip(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class SplitView : Control {
internal SplitView(Window w, ulong h) : base(w,h) { }
public double Ratio { get { var v = Features.Get(this,35); return v.A; } set => Features.Set(this,35,a: value); }
public SplitView SetRatio(double value) { Ratio = value; return this; }
public bool SecondVisible { get { var v = Features.Get(this,44); return v.First != 0; } set => Features.Set(this,44,first: value ? 1u : 0u); }
public SplitView SetSecondVisible(bool value) { SecondVisible = value; return this; }
}
public sealed unsafe partial class PageView : Element {
internal PageView(Window w, ulong h) : base(w,h) { }
public ulong SelectedPage { set => Features.Set(this,36,first: value); }
public PageView SetSelectedPage(ulong value) { SelectedPage = value; return this; }
}
public sealed unsafe partial class DataGrid : Control {
internal DataGrid(Window w, ulong h) : base(w,h) { }
public double Offset { get { var v = Features.Get(this,29); return v.A; } set => Features.Set(this,29,a: value); }
public DataGrid SetOffset(double value) { Offset = value; return this; }
public void SelectAll() => Features.Action(this,15);
}
public sealed unsafe partial class HistoryChart : Control {
internal HistoryChart(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class NavigationView : Control {
internal NavigationView(Window w, ulong h) : base(w,h) { }
public bool Expanded { get { var v = Features.Get(this,5); return v.First != 0; } set => Features.Set(this,5,first: value ? 1u : 0u); }
public NavigationView SetExpanded(bool value) { Expanded = value; return this; }
}
public sealed unsafe partial class MillerColumns : Control {
internal MillerColumns(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class ToggleSwitch : Control {
internal ToggleSwitch(Window w, ulong h) : base(w,h) { }
public bool Checked { get { var v = Features.Get(this,46); return v.First != 0; } set => Features.Set(this,46,first: value ? 1u : 0u); }
public ToggleSwitch SetChecked(bool value) { Checked = value; return this; }
}
public sealed unsafe partial class ToggleButton : Control {
internal ToggleButton(Window w, ulong h) : base(w,h) { }
public bool Checked { get { var v = Features.Get(this,10); return v.First != 0; } set => Features.Set(this,10,first: value ? 1u : 0u); }
public ToggleButton SetChecked(bool value) { Checked = value; return this; }
public ButtonIcon Icon { get { var v = Features.Get(this,45); return (ButtonIcon)v.First; } set => Features.Set(this,45,first: (uint)value); }
public ToggleButton SetIcon(ButtonIcon value) { Icon = value; return this; }
}
public sealed unsafe partial class ProgressRing : Control {
internal ProgressRing(Window w, ulong h) : base(w,h) { }
public NumericRange Range { get { var v = Features.Get(this,1); return new(v.A,v.B,v.C,v.D); } set => Features.Set(this,1,a: value.Minimum, b: value.Maximum, c: value.SmallStep, d: value.LargeStep); }
public ProgressRing SetRange(NumericRange value) { Range = value; return this; }
public double Value { get { var v = Features.Get(this,2); return v.A; } set => Features.Set(this,2,a: value); }
public ProgressRing SetValue(double value) { Value = value; return this; }
public ProgressState State { get { var v = Features.Get(this,6); return (ProgressState)v.First; } set => Features.Set(this,6,first: (uint)value); }
public ProgressRing SetState(ProgressState value) { State = value; return this; }
}
public sealed unsafe partial class CheckBox : Control {
internal CheckBox(Window w, ulong h) : base(w,h) { }
public CheckState State { get { var v = Features.Get(this,48); return (CheckState)v.First; } set => Features.Set(this,48,first: (uint)value); }
public CheckBox SetState(CheckState value) { State = value; return this; }
public bool ThreeState { get { var v = Features.Get(this,49); return v.First != 0; } set => Features.Set(this,49,first: value ? 1u : 0u); }
public CheckBox SetThreeState(bool value) { ThreeState = value; return this; }
}
public sealed unsafe partial class HyperlinkButton : Control {
internal HyperlinkButton(Window w, ulong h) : base(w,h) { }
public ButtonIcon Icon { get { var v = Features.Get(this,45); return (ButtonIcon)v.First; } set => Features.Set(this,45,first: (uint)value); }
public HyperlinkButton SetIcon(ButtonIcon value) { Icon = value; return this; }
}
public sealed unsafe partial class SelectorBar : Control {
internal SelectorBar(Window w, ulong h) : base(w,h) { }
}
public sealed unsafe partial class InfoBadge : Control {
internal InfoBadge(Window w, ulong h) : base(w,h) { }
public uint Count { get { var v = Features.Get(this,52); return checked((uint)v.First); } set => Features.Set(this,52,first: value); }
public InfoBadge SetCount(uint value) { Count = value; return this; }
public ButtonIcon Icon { get { var v = Features.Get(this,53); return (ButtonIcon)v.First; } set => Features.Set(this,53,first: (uint)value); }
public InfoBadge SetIcon(ButtonIcon value) { Icon = value; return this; }
public void SetDot() => Features.Action(this,18);
}
public sealed unsafe partial class MenuBar : Control {
internal MenuBar(Window w, ulong h) : base(w,h) { }
}
