set(XUI_LSH_PACKAGE_DIR "" CACHE PATH "Extracted Lsh 0.3.0 NuGet package; empty disables LSH")
option(XUI_REQUIRE_LSH "Fail configuration if LSH syntax highlighting is unavailable" OFF)
if(XUI_REQUIRE_LSH AND NOT XUI_LSH_PACKAGE_DIR)
    message(FATAL_ERROR "LSH syntax highlighting was requested. Set XUI_LSH_PACKAGE_DIR to an extracted Lsh 0.3.0 package. See CONTRIBUTING.md.")
endif()
target_sources(xui_windows PRIVATE src/syntax_highlighting.cpp)
if(XUI_LSH_PACKAGE_DIR)
    foreach(required build/native/include/lsh.h licenses/LSH-LICENSE.txt Lsh.nuspec)
        if(NOT EXISTS "${XUI_LSH_PACKAGE_DIR}/${required}")
            message(FATAL_ERROR "Incomplete Lsh 0.3.0 package: ${XUI_LSH_PACKAGE_DIR}/${required}")
        endif()
    endforeach()
    file(READ "${XUI_LSH_PACKAGE_DIR}/Lsh.nuspec" nuspec)
    if(NOT nuspec MATCHES "<version>0\\.3\\.0</version>")
        message(FATAL_ERROR "XUI requires the Lsh 0.3.0 package")
    endif()
    if(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$" OR MSVC_CXX_ARCHITECTURE_ID STREQUAL "ARM64")
        set(XUI_LSH_ARCH arm64)
    else()
        set(XUI_LSH_ARCH x64)
    endif()
    set(XUI_LSH_DLL "${XUI_LSH_PACKAGE_DIR}/runtimes/win-${XUI_LSH_ARCH}/native/lsh_lib.dll")
    if(NOT EXISTS "${XUI_LSH_DLL}")
        message(FATAL_ERROR "LSH runtime not found: ${XUI_LSH_DLL}")
    endif()
    set(grammar_files "${CMAKE_CURRENT_SOURCE_DIR}/integrations/edit-lsh/xui.lsh")
    foreach(language c cpp csharp rust)
        list(APPEND grammar_files "${CMAKE_CURRENT_SOURCE_DIR}/integrations/edit-lsh/upstream/${language}.lsh")
    endforeach()
    set(XUI_LSH_GRAMMAR "std::string{}")
    foreach(grammar IN LISTS grammar_files)
        file(READ "${grammar}" source)
        string(APPEND XUI_LSH_GRAMMAR " + R\"XUI_LSH(\n${source}\n)XUI_LSH\"")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${grammar_files})
    configure_file(integrations/lsh/grammar.hpp.in generated/lsh_grammar.hpp @ONLY)
    target_include_directories(xui_windows PRIVATE "${XUI_LSH_PACKAGE_DIR}/build/native/include" "${CMAKE_CURRENT_BINARY_DIR}/generated")
    target_compile_definitions(xui_windows PRIVATE XUI_ENABLE_LSH=1)
    # All native executables and xui.dll use the same configuration output directory.
    add_custom_command(TARGET xui_windows POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XUI_LSH_DLL}" "$<TARGET_FILE_DIR:xui_windows>/lsh_lib.dll"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt" "$<TARGET_FILE_DIR:xui_windows>/LSH-LICENSE.txt")
    install(FILES "${XUI_LSH_DLL}" "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt"
        DESTINATION . COMPONENT Samples)
    install(FILES "${XUI_LSH_DLL}" "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt"
        DESTINATION . COMPONENT Native)
endif()
