option(XUI_ENABLE_LSH "Enable syntax highlighting with the bundled Lsh package" ON)
set(XUI_LSH_PACKAGE_DIR "" CACHE PATH "Extracted Lsh 0.3.0 NuGet package override; empty uses dep/Lsh.0.3.0.nupkg")
option(XUI_REQUIRE_LSH "Fail configuration if LSH syntax highlighting is unavailable" OFF)
target_sources(xui_windows PRIVATE src/syntax_highlighting.cpp)
if(XUI_REQUIRE_LSH AND NOT XUI_ENABLE_LSH)
    message(FATAL_ERROR "XUI_REQUIRE_LSH=ON conflicts with XUI_ENABLE_LSH=OFF. See CONTRIBUTING.md.")
endif()
if(XUI_ENABLE_LSH)
    if(NOT XUI_LSH_PACKAGE_DIR)
        set(package "${CMAKE_CURRENT_SOURCE_DIR}/dep/Lsh.0.3.0.nupkg")
        if(NOT EXISTS "${package}")
            message(FATAL_ERROR "Missing bundled LSH package: ${package}. Restore the checked-in dep directory, set XUI_LSH_PACKAGE_DIR, or explicitly set XUI_ENABLE_LSH=OFF.")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${package}")
        file(SHA256 "${package}" package_hash)
        set(XUI_LSH_PACKAGE_DIR "${CMAKE_CURRENT_BINARY_DIR}/packages/lsh/${package_hash}")
        if(NOT EXISTS "${XUI_LSH_PACKAGE_DIR}/.xui-extracted")
            file(ARCHIVE_EXTRACT INPUT "${package}" DESTINATION "${XUI_LSH_PACKAGE_DIR}")
            file(WRITE "${XUI_LSH_PACKAGE_DIR}/.xui-extracted" "${package_hash}\n")
        endif()
    endif()
    foreach(required build/native/include/lsh.h licenses/LSH-LICENSE.txt Lsh.nuspec)
        if(NOT EXISTS "${XUI_LSH_PACKAGE_DIR}/${required}")
            message(FATAL_ERROR "Incomplete Lsh 0.3.0 package: ${XUI_LSH_PACKAGE_DIR}/${required}")
        endif()
    endforeach()
    file(READ "${XUI_LSH_PACKAGE_DIR}/Lsh.nuspec" nuspec)
    if(NOT nuspec MATCHES "<version>0\\.3\\.0</version>")
        message(FATAL_ERROR "XUI requires the Lsh 0.3.0 package")
    endif()
    if(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$" OR MSVC_CXX_ARCHITECTURE_ID STREQUAL "ARM64")
        set(XUI_LSH_ARCH arm64)
    else()
        set(XUI_LSH_ARCH x64)
    endif()
    set(XUI_LSH_DLL "${XUI_LSH_PACKAGE_DIR}/runtimes/win-${XUI_LSH_ARCH}/native/lsh_lib.dll")
    if(NOT EXISTS "${XUI_LSH_DLL}")
        message(FATAL_ERROR "LSH runtime not found: ${XUI_LSH_DLL}")
    endif()
    set(grammar_files "${CMAKE_CURRENT_SOURCE_DIR}/integrations/edit-lsh/xui.lsh")
    foreach(language c cpp csharp rust)
        list(APPEND grammar_files "${CMAKE_CURRENT_SOURCE_DIR}/integrations/edit-lsh/upstream/${language}.lsh")
    endforeach()
    set(XUI_LSH_GRAMMAR "std::string{}")
    foreach(grammar IN LISTS grammar_files)
        file(READ "${grammar}" source)
        string(APPEND XUI_LSH_GRAMMAR " + R\"XUI_LSH(\n${source}\n)XUI_LSH\"")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${grammar_files})
    configure_file(integrations/lsh/grammar.hpp.in generated/lsh_grammar.hpp @ONLY)
    target_include_directories(xui_windows PRIVATE "${XUI_LSH_PACKAGE_DIR}/build/native/include" "${CMAKE_CURRENT_BINARY_DIR}/generated")
    target_compile_definitions(xui_windows PRIVATE XUI_ENABLE_LSH=1)
    # All native executables and xui.dll use the same configuration output directory.
    add_custom_command(TARGET xui_windows POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XUI_LSH_DLL}" "$<TARGET_FILE_DIR:xui_windows>/lsh_lib.dll"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt" "$<TARGET_FILE_DIR:xui_windows>/LSH-LICENSE.txt")
    install(FILES "${XUI_LSH_DLL}" "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt"
        DESTINATION . COMPONENT Samples)
    install(FILES "${XUI_LSH_DLL}" "${XUI_LSH_PACKAGE_DIR}/licenses/LSH-LICENSE.txt"
        DESTINATION . COMPONENT Native)
endif()
