"""Generate the feature FFI from its C declaration and typed facades from features.json."""
import json
import re
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parent.parent
manifest = json.loads((root / "bindings" / "features.json").read_text())
header = (root / "include" / "xui" / "xui_features.h").read_text()
header = re.sub(r"/\*.*?\*/", "", header, flags=re.S)


def pascal(s):
    return "".join(p[:1].upper() + p[1:] for p in s.removeprefix("xui_").split("_"))


def snake(s):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()


basic_cs = {"uint32_t": "uint", "uint64_t": "ulong", "float": "float", "double": "double",
            "char": "byte", "void": "void", "xui_status": "int", "xui_handle": "ulong",
            "xui_string": "Text", "xui_window_options": "Options"}
basic_rs = {"uint32_t": "u32", "uint64_t": "u64", "float": "f32", "double": "f64",
            "char": "u8", "void": "c_void", "xui_status": "i32", "xui_handle": "u64",
            "xui_string": "Text", "xui_window_options": "Options"}
callbacks_cs = {
    "xui_window_icon_error_callback": "delegate* unmanaged[Cdecl]<nint, byte*, uint, int>",
    "xui_miller_callback": "delegate* unmanaged[Cdecl]<nint, MillerEvent*, int>",
    "xui_source_visual_query": "delegate* unmanaged[Cdecl]<nint, ulong, ulong, uint*, byte*, uint, uint*, int>",
    "xui_callback": "delegate* unmanaged[Cdecl]<nint, Event*, int>",
    "xui_key_handler": "delegate* unmanaged[Cdecl]<nint, KeyEvent*, uint*, int>",
    "xui_navigation_handler": "delegate* unmanaged[Cdecl]<nint, NavigationEvent*, uint*, int>",
    "xui_post_callback": "delegate* unmanaged[Cdecl]<nint, uint, int>",
    "xui_secret_receiver": "delegate* unmanaged[Cdecl]<nint, byte*, uint, int>",
    "xui_source_query": "delegate* unmanaged[Cdecl]<nint, uint, ulong, ulong, SourceRow*, int>",
    "xui_context_ref": "delegate* unmanaged[Cdecl]<nint, void>"
}


def typ(c, rust=False):
    c = c.strip()
    const = c.startswith("const ")
    c = c.removeprefix("const ").strip()
    pointer = c.endswith("*")
    base = c.rstrip("*").strip()
    if rust:
        t = basic_rs.get(base, pascal(base))
        return ("*const " if const else "*mut ") + t if pointer else t
    if base in callbacks_cs:
        return callbacks_cs[base]
    if base == "void" and pointer:
        return "nint"
    return basic_cs.get(base, pascal(base)) + ("*" if pointer else "")


cs = ["// Generated by bindings/generate_features.py. Do not edit.",
      "using System.Runtime.InteropServices;", "namespace Xui;", "internal static unsafe partial class Native {"]
rs = ["// Generated by bindings/generate_features.py. Do not edit.",
      "use super::*;",
      'pub type WindowIconErrorCallback = Option<unsafe extern "C" fn(*mut c_void, *const u8, u32) -> i32>;',
      'pub type MillerCallback = Option<unsafe extern "C" fn(*mut c_void, *const MillerEvent) -> i32>;',
      'pub type SourceVisualQuery = Option<unsafe extern "C" fn(*mut c_void, u64, u64, *mut u32, *mut u8, u32, *mut u32) -> i32>;',
      'pub type KeyHandler = Option<unsafe extern "C" fn(*mut c_void, *const KeyEvent, *mut u32) -> i32>;',
      'pub type NavigationHandler = Option<unsafe extern "C" fn(*mut c_void, *const NavigationEvent, *mut u32) -> i32>;',
      'pub type PostCallback = Option<unsafe extern "C" fn(*mut c_void, u32) -> i32>;',
      'pub type SecretReceiver = Option<unsafe extern "C" fn(*mut c_void, *const u8, u32) -> i32>;',
      'pub type SourceQuery = Option<unsafe extern "C" fn(*mut c_void, u32, u64, u64, *mut SourceRow) -> i32>;',
      'pub type ContextRef = Option<unsafe extern "C" fn(*mut c_void)>;']
for name, body in re.findall(r"typedef struct (xui_\w+)\s*\{(.*?)\}\s*\w+;", header, re.S):
    cs += ["[StructLayout(LayoutKind.Sequential)]", f"internal struct {pascal(name)} {{"]
    rs += ["#[repr(C)]", "#[derive(Clone, Copy)]", f"pub struct {pascal(name)} {{"]
    for decl in body.split(";"):
        if not decl.strip():
            continue
        m = re.match(r"\s*((?:const\s+)?\w+\s*\*?)\s+(.+)", decl.strip())
        ctype, names = m.groups()
        for variable in names.split(","):
            m = re.fullmatch(r"\s*(\w+)(?:\[(\d+)\])?\s*", variable)
            field, array = m.groups()
            cs.append(f"internal {'fixed ' if array else ''}{typ(ctype)} {pascal(field)}{f'[{array}]' if array else ''};")
            rt = typ(ctype, True)
            rs.append(f"pub {field}: {f'[{rt}; {array}]' if array else rt},")
    cs.append("}")
    rs += ["}", f"impl Default for {pascal(name)} {{ fn default() -> Self {{ unsafe {{ std::mem::zeroed() }} }} }}"]
rs.append('unsafe extern "C" {')
for ret, name, args in re.findall(r"XUI_API (\w+) XUI_CALL (\w+)\((.*?)\) XUI_NOEXCEPT;", header, re.S):
    ca, ra = [], []
    for arg in args.split(","):
        if arg.strip() == "void":
            continue
        m = re.match(r"\s*(.*?)\s+(\w+)\s*$", arg, re.S)
        t, a = m.groups()
        ca.append(f"{typ(t)} @{a}")
        ra.append(f"{a if a not in ['type'] else 'r#type'}: {typ(t, True)}")
    cs += [f'[LibraryImport("xui", EntryPoint = "{name}")]',
           f"internal static partial {typ(ret)} {pascal(name)}({', '.join(ca)});"]
    rs.append(f"pub fn {name}({', '.join(ra)}) -> {typ(ret, True)};")
cs.append("}")
rs.append("}")
(root / "bindings/dotnet/Xui/Native.Features.g.cs").write_text("\n".join(cs) + "\n")
(root / "bindings/rust/xui-sys/src/features.rs").write_text("\n".join(rs) + "\n")

cs = ["// Generated by bindings/generate_features.py. Do not edit.", "namespace Xui;",
      "public sealed unsafe partial class Window {"]
rs = ["// Generated by bindings/generate_features.py. Do not edit.", "use super::*;"]
for name, kind, category in manifest["controls"]:
    params = 'string name'
    args = "name"
    rparams = "name: &str"
    rargs = "name"
    if category in ["content", "contentPopup", "target"]:
        params += ", Element content"
        args += ", content"
        rparams += ", content: &Element"
        rargs += ", Some(content), None, 0"
    elif category in ["two", "twoControl"]:
        params += ", Element first, Element second"
        args += ", first, second"
        rparams += ", first: &Element, second: &Element"
        rargs += ", Some(first), Some(second), 0"
    elif category == "combo":
        params += ", bool editable = false"
        args += ", mode: editable ? 1u : 0u"
        rparams += ", editable: bool"
        rargs += ", None, None, editable as u32"
    elif category == "date":
        params += ", DateTimePresentation presentation = DateTimePresentation.Date"
        args += ", mode: (uint)presentation"
        rparams += ", presentation: DateTimePresentation"
        rargs += ", None, None, presentation as u32"
    else:
        rargs += ", None, None, 0"
    cs.append(f"public {name} {name}({params}) => new(this, FeatureCreate({kind}, {args}));")
    rs.append(f"impl Window {{ pub fn {snake(name)}(&self, {rparams}) -> Result<{name}> {{ self.feature_create({kind}, {rargs}).map({name}) }} }}")
cs.append("}")
for name, kind, category in manifest["controls"]:
    base = "Element" if category in ["panel", "two", "popup", "target", "contentPopup", "secret"] else "Control"
    cs += [f"public sealed unsafe partial class {name} : {base} {{",
           f"internal {name}(Window w, ulong h) : base(w,h) {{ }}"]
    rs += [f"#[derive(Clone)] pub struct {name}(pub(crate) Element);"]
    rs += [f"pub struct Weak{name}(WeakElement);",
           f"impl Weak{name} {{ pub fn upgrade(&self) -> Option<{name}> {{ self.0.upgrade().map({name}) }} }}",
           f"impl {name} {{ pub fn weak(&self) -> Weak{name} {{ Weak{name}(self.0.downgrade()) }} }}"]
    if category == "secret":
        rs += [f"impl {name} {{ pub fn as_element(&self) -> &Element {{ &self.0 }} }}"]
    else:
        rs += [f"impl std::ops::Deref for {name} {{ type Target = Element; fn deref(&self) -> &Element {{ &self.0 }} }}"]
    for types, member, prop, shape, getter in manifest["members"]:
        if name not in types:
            continue
        ct = {"range": "NumericRange", "selection": "TextSelection", "color": "RgbaColor"}.get(shape, shape)
        rt = {"double": "f64", "ulong": "u64", "range": "NumericRange", "selection": "TextSelection",
              "color": "RgbaColor", "string": "&str"}.get(shape, shape)
        cexpr, rexpr = "", ""
        cg, rg = "", ""
        if shape == "double":
            cexpr, rexpr, cg, rg = "a: value", "a: value", "v.A", "v.a"
        elif shape == "bool":
            cexpr, rexpr, cg, rg = "first: value ? 1u : 0u", "first: value as u64", "v.First != 0", "v.first != 0"
        elif shape == "ulong":
            cexpr, rexpr, cg, rg = "first: value", "first: value", "v.First", "v.first"
        elif shape == "string":
            cexpr, rexpr = "text: value", "text: text(value)?"
        elif shape == "range":
            cexpr = "a: value.Minimum, b: value.Maximum, c: value.SmallStep, d: value.LargeStep"
            rexpr = "a: value.minimum, b: value.maximum, c: value.small_step, d: value.large_step"
            cg = "new(v.A,v.B,v.C,v.D)"
            rg = "NumericRange { minimum:v.a, maximum:v.b, small_step:v.c, large_step:v.d }"
        elif shape == "selection":
            cexpr, rexpr = "first: value.Start, second: value.End", "first: value.start, second: value.end"
            cg, rg = "new(v.First,v.Second)", "TextSelection { start:v.first, end:v.second }"
        elif shape == "color":
            cexpr, rexpr = "first: value.Packed", "first: value.packed()"
            cg, rg = "RgbaColor.FromPacked(v.First)", "RgbaColor::from_packed(v.first)"
        else:
            cexpr, rexpr, cg = "first: (uint)value", "first: value as u64", f"({ct})v.First"
            rg = f"{rt}::from_native(v.first)?"
        gs = f"get {{ var v = Features.Get(this,{prop}); return {cg}; }} " if getter else ""
        cs.append(f"public {ct} {member} {{ {gs}set => Features.Set(this,{prop},{cexpr}); }}")
        cs.append(f"public {name} Set{member}({ct} value) {{ {member} = value; return this; }}")
        rs.append(f"impl {name} {{ pub fn set_{snake(member)}(&self, value: {rt}) -> Result<()> {{ self.0.feature_set({prop}, sys::FeatureValue {{ {rexpr}, ..value_record() }}) }} }}")
        if getter:
            result = rg[:-1] if rg.endswith("?") else f"Ok({rg})"
            rs.append(f"impl {name} {{ pub fn {snake(member)}(&self) -> Result<{rt}> {{ let v = self.0.feature_get({prop})?; {result} }} }}")
    for types, method, action in manifest["actions"]:
        if name in types:
            cs.append(f"public void {method}() => Features.Action(this,{action});")
            rs.append(f"impl {name} {{ pub fn {snake(method)}(&self) -> Result<()> {{ self.0.feature_action({action},0,0) }} }}")
    cs.append("}")
(root / "bindings/dotnet/Xui/Features.g.cs").write_text("\n".join(cs) + "\n")
(root / "bindings/rust/xui/src/features_generated.rs").write_text("\n".join(rs) + "\n")
subprocess.run(["rustfmt", "--edition", "2024",
                str(root / "bindings/rust/xui-sys/src/features.rs"),
                str(root / "bindings/rust/xui/src/features_generated.rs")], check=True)
